Feature/ufs 243 int application questions
ukriorg/ukripoc-opportunity pull request #16
Opened 2019-06-03 16:03 UTC by aerian-darren

2 anys todo
add in complete

2019-06-03 20:32 UTC, ascorbic requested changes

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestion/ApplicationQuestion.tsx
> +        heading: applicationQuestion.heading,
All you're doing here is copying `applicationQuestion`. You could replace all of this with `useState(        question && question.getApplicationQuestion || defaultState)`

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestion/ApplicationQuestion.tsx
> +    const applicationId = question.getApplicationQuestion.application!.id;
Can you check for `application`. You shoudl only use `!` if you're absolutely certain that the property will exist, which can't be the case when it's data being loaded. Otherwise you risk runtime errors.

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestion/ApplicationQuestion.tsx
> +    const handleSubmit = (event: SyntheticEvent) => {
Wrap this in `useCallback`

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestion/ApplicationQuestion.tsx
> +                    onChange={(event: SyntheticEvent<HTMLInputElement>) =>
No need for the arrow function here. Just do `onChange={onChecked}`

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestionsList/ApplicationQuestionsList.tsx
> +            <Caption> Application questions </Caption>
Remove the spaces around the text

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestionsList/ApplicationQuestionsList.tsx
> +                        (question: UpdateApplicationQuestionInput | null) => {
You shouldn't need to type this: it should be able to infer the type from the type of `questions`. Is it complaining if you leave it out?

2019-06-03 20:32 UTC, ascorbic commented on src/components/ApplicationQuestionsList/ApplicationQuestionsList.tsx
> +                                return (
Just ` if(question) {` is fine. That'll catch other falsy conditions too.

2019-06-03 20:32 UTC, ascorbic commented on src/components/CreateApplicationQuestion/CreateApplicationQuestion.tsx
> +        applicationQuestionApplicationId: "b762afaa-7625-4c22-9d14-e1ca501b8cf0"
What's going on here?

2019-06-03 20:32 UTC, ascorbic commented on src/components/SetupApplication/SetupApplication.tsx
> +    if (!application || !application.getApplication) {
You can remove this, as you're already checking for it below.

2019-06-03 20:32 UTC, ascorbic commented on src/components/SetupApplication/SetupApplicationForm.tsx
> +    useEffect(() => {
Rather than the `validSoFar` stuff, could you just setValidForm(false) as soon as it's invalid, and return early?

2019-06-03 23:16 UTC, aerian-darren commented
Fixed items mentioned

2019-06-04 08:15 UTC, ascorbic approved these changes

2019-06-04 08:16 UTC, merged