Feature/demo snag list
ukriorg/ukripoc-opportunity pull request #17
Opened 2019-06-04 09:07 UTC by aerian-darren

Todo:  validation on date

2019-06-04 10:59 UTC, ascorbic requested changes

2019-06-04 10:59 UTC, ascorbic commented on src/components/AllOpportunities/AllOpportunities.tsx
> +                                                    {" "}
You can remove these spaces

2019-06-04 10:59 UTC, ascorbic commented on src/components/WebsiteListing/WebsiteListing.tsx
> +        return <div> Loading... </div>;
Do you need to do this? Could we wrap the form with a LoadingBox instead?

2019-06-04 16:43 UTC, ascorbic requested changes

2019-06-04 16:43 UTC, ascorbic commented on src/components/WebsiteListing/WebsiteListing.tsx
> +    if (!websiteListing) {
I meant a LoadingBox wrapping the form.

2019-06-05 15:19 UTC, aerian-darren commented on src/components/WebsiteListing/WebsiteListing.tsx
> +    if (!websiteListing) {
Fixed.

2019-06-06 08:13 UTC, ascorbic requested changes

2019-06-06 08:13 UTC, ascorbic commented on src/components/SetupApplication/SetupApplicationForm.tsx
> +            setDateError("Open date must be before today");
Surely _after_ today

2019-06-06 10:48 UTC, ascorbic approved these changes

2019-06-06 11:11 UTC, merged